[build-system]
requires = ["flit_scm"]
build-backend = "flit_scm:buildapi"

[project]
name = "wi1_bot"
description = "Discord bot for Radarr/Sonarr integration"
authors = [{ name = "William Huebner", email = "wilhueb@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10"
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "discord.py==1.7.3",
    "Flask==2.1.2",
    "mongoengine==0.24.1",
    "pyarr==3.1.3",
    "pymongo==4.1.1",
    "python-pushover==0.4",
    "PyYAML==6.0"
]

[project.optional-dependencies]
dev = [
    "black==22.3.0",
    "discord.py-stubs==1.7.3",
    "flake8==4.0.1",
    "flit==3.7.1",
    "isort==5.10.1",
    "mongo-types==0.15.1",
    "mypy==0.950",
    "pre-commit==2.19.0",
    "setuptools-scm==6.4.2",
    "types-PyYAML==6.0.7"
]

[project.urls]
Source = "https://github.com/wthueb/wi1-bot"

[project.scripts]
wi1-bot = "wi1_bot.scripts.start:main"
transcode-item = "wi1_bot.scripts.transcode_item:main"
add-tag = "wi1_bot.scripts.add_tag:main"

[tool.setuptools_scm]
write_to = "wi1_bot/_version.py"

[tool.mypy]
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "pushover",
    "pyarr",
    "setuptools_scm"
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
known_first_party = "wi1_bot"
