[build-system]
requires = ["setuptools==61.*", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "wi1-bot"
description = "Discord bot for Radarr/Sonarr integration"
authors = [{ name = "William Huebner", email = "wilhueb@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10"
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "discord.py==2.0.1",
    "Flask==2.1.2",
    "mongoengine==0.24.1",
    "pyarr==3.1.3",
    "python-pushover==0.4",
    "PyYAML==6.0",
    "websockets==10.3"
]

[project.optional-dependencies]
dev = [
    "black==22.3.0",
    "flake8==4.0.1",
    "isort==5.10.1",
    "mongo-types==0.15.1",
    "mypy==0.982",
    "pre-commit==2.19.0",
    "requests==2.27.1",
    "types-PyYAML==6.0.7",
    "types-requests==2.27.29"
]

[project.urls]
Homepage = "https://github.com/wthueb/wi1-bot"

[project.scripts]
wi1-bot = "wi1_bot.scripts.start:main"
transcode-item = "wi1_bot.scripts.transcode_item:main"

[tool.setuptools]
packages = ["wi1_bot"]

[tool.setuptools_scm]
write_to = "wi1_bot/_version.py"

# [tool.mypy]
# namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "pushover",
    "pyarr",
    "setuptools_scm"
]
ignore_missing_imports = true

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
known_first_party = ["wi1_bot"]
